<?xml version="1.0" encoding="utf-8"?><Database Name="SLDatabase" Class="PubsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=cs1;Initial Catalog=SLDatabase;User ID=SLApp" SettingsObjectName="SLApp_Beta.Properties.Settings" SettingsPropertyName="SLDatabaseConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Types_of_Service" Member="Types_of_Services">
    <Type Name="Types_of_Service">
      <Column Name="CommunityBasedResearch" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LongTerm" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShortTerm" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Agency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Application_Users" Member="Application_Users">
    <Type Name="Application_User">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Community_Partnership_Agreement" Member="Community_Partnership_Agreements">
    <Type Name="Community_Partnership_Agreement">
      <Column Name="DateSigned" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PDF" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AgencyName" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Learning_Experience" Member="Learning_Experiences">
    <Type Name="Learning_Experience">
      <Column Name="Student_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CourseNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Section" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Professor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Semester" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalHours" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeofLearning" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ConfirmedHours" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LiabilityWaiver" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProjectAgreement" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TimeLog" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="Student_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GraduationYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Types_of_Notes" Member="Types_of_Notes">
    <Type Name="Types_of_Note">
      <Column Name="AgencyVisittoCampus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AgencyComplaint" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FeedbackFromAgency" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FeedbackFromFaculty" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FeedbackFromStudent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IncidentReport" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SLFair" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StudentPlacement" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VisittoAgency" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Agency" Member="Agencies">
    <Type Name="Agency">
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CoordinatorName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AlternateContact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FaxNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WebsiteLink" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StreetAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Rating" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>