<?xml version="1.0" encoding="utf-8"?><Database Name="SLDatabase_Home" Class="PubsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=GABRIEL-PC;Initial Catalog=SLDatabase_Home;Integrated Security=True" SettingsObjectName="SLApp_Beta.Properties.Settings" SettingsPropertyName="SLDatabase_HomeConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Course" Member="Courses">
    <Type Name="Course">
      <Column Name="CourseNumber" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CourseName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Section" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Professor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="Student_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GraduationYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Learning_Experience" Member="Learning_Experiences">
    <Type Name="Learning_Experience">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Student_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Semester" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalHours" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeofLearning" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ConfirmedHours" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LiabilityWaiver" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProjectAgreement" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TimeLog" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>